server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
      - CustomFilter
      - AddRequestHeader=global-request, global-request-header
      - AddResponseHeader=global-response, global-response-header
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/employee/**
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/consumer/**